version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "profile-page"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123123"
      MYSQL_ROOT_PASSWORD: "123123"
    ports:
      - 127.0.0.1:3307:3306
    networks:
      - LAMP

networks:
  LAMP:
    driver: bridge
    external: true
